<?php
/**
 * @var $block \PeterBrain\SalableQty\Block\SalableQuantityBlock
 */
?>
<?php if ($block->isEnabled()): ?>

    <?php $salable_qty = $block->getSalableQuantity(); ?>
    <?php $message = $block->getSalableQuantityMessage(); ?>

    <?php if (!empty($message)): ?>
        <div class="product-salable-quantity">
            <?= /* @noEscape */ $message; ?>
        </div>
    <?php endif; ?>

    <?php if ($block->getDisableAddToCartButton() && $salable_qty < 1 && is_numeric($salable_qty)): ?>
        <script>
            var cartButton = document.getElementById('product-addtocart-button');

            if (cartButton != null) {
                window.addEventListener('load', (event) => {
                    cartButton.disabled = true;
                    cartButton.classList.add("disabled", "addToCartButtonDisabledClass");
                    <?= !$block->getEnableIcon() ?: 'cartButton.classList.add("lock-icon");'; ?>
                });
            }
        </script>
    <?php endif; ?>

<?php endif; ?>
